projects:
  hirehelperbackend:
    schemaPath: >-
      C:/Users/nirup/AWS_Integration/HireHelper_frontend/app/src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
extensions:
  amplify:
    version: 3
